[project]
name = "my_python_utils"
version = "0.1.0"
description = "自作のpythonユーティリティライブラリ"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "setuptools>=80.9.0",
]
